### PR TITLE
 Add amqp subscriber

### PR DESCRIPTION
**Pull request by takahashi-tsc**

### CODE REVIEW

**Comment by yu-kasuya** [comment]
Thank you. Could you explain the environment that amqp.go work? Is rabbitMQ necessary?

**Comment by takahashi-tsc** [comment]
> Could you explain the environment that amqp.go work? Is rabbitMQ necessary?

Yes, I use RabbitMQ in OpenStack. I'll check the "transport_url" in nova.conf to know URI, username, and password. URI and username is hard-coding. Input password as an environment variable.
(I think that all  should be config...)

As I said in #9, I'll write the document on how to use.

**Comment by takahashi-tsc** [comment]
I've written getting started.
If you try pubsub, you have to checkout add-pubsub branch after go get.

I will fix the following later. (I want to make it a different branch)

- Parameter configuration
- Use RPC (Now, use simple text messaging), in order to surely complete the setting

**Comment by yu-kasuya** [comment]
Thank you for writing a detail document, I'll try it!

**Comment by yu-kasuya** [comment]
Is golang version over 1.7? I use 1.6.2 now, which version is better?

**Comment by takahashi-tsc** [comment]
I use 1.8.3. What problems does your environment have?
I think golang 1.8 is better. It is stable and latest package, since it can be installed with yum

```
$ go version
go version go1.8.3 linux/amd64
$ yum list installed | grep golang
golang.x86_64                   1.8.3-1.el7              @base
golang-bin.x86_64               1.8.3-1.el7              @base
golang-src.noarch               1.8.3-1.el7              @base
```

**Comment by yu-kasuya** [comment]
Like context pkg is not standard pkg in 1.6.x. So there are some dependencies of pkg. I'll try in 1.8.3.

**Pull request merged**
